---
# Application Configuration
web_app_name: devops-app
web_app_docker_image: iliadocker21/devops-info-python
web_app_docker_tag: latest
web_app_port: 8000
web_app_internal_port: 8080

# Docker Compose Config
web_app_compose_project_dir: "/opt/{{ web_app_name }}"
web_app_docker_compose_version: "3.8"

# Common role configuration
common_packages:
  - python3-pip
  - curl
  - git
  - vim
  - htop
  - wget
  - net-tools
  - jq

common_app_user: appuser
common_app_user_sudoer: false

# Docker Compose environment variables
web_app_environment:
  ENVIRONMENT: production
