{{- if and .Values.hooks.enabled .Values.hooks.preInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-info-python.fullname" . }}-pre-install"
  labels:
    {{- include "devops-info-python.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ .Values.hooks.preInstall.weight }}"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "devops-info-python.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-check
          image: {{ default (printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion)) .Values.hooks.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - {{ .Values.hooks.preInstall.command | quote }}
{{- end }}
