replicaCount: 1

image:
  tag: "lab9"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30081

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 5
