{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info-python.fullname" . }}-app-credentials
  labels:
    {{- include "devops-info-python.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.secrets.username | quote }}
  password: {{ .Values.secrets.password | quote }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  api-key: {{ .Values.secrets.apiKey | quote }}
{{- end }}
